name: Invoice Automation

on:
  schedule:
    # Runs at 7:10 AM Melbourne time (21:10 UTC previous day)
    - cron: '10 21 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  create-invoices:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install numpy==1.24.3
        pip install pandas==1.5.3
        pip install -r requirements.txt

    - name: Create and verify credentials
      run: |
        # Create credentials.json
        echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json
        
        # Debug checks (will mask sensitive info)
        echo "Checking if credentials.json exists:"
        ls -la credentials.json
        
        echo "Checking credentials.json structure (will hide sensitive values):"
        python -c "
        import json
        with open('credentials.json', 'r') as f:
            creds = json.load(f)
            print('Keys present in credentials.json:', list(creds.keys()))
            print('Project ID:', creds.get('project_id', 'NOT FOUND'))
            print('Auth URI:', creds.get('auth_uri', 'NOT FOUND'))
        "

    - name: Run invoice creation
      env:
        XERO_CLIENT_ID: ${{ secrets.XERO_CLIENT_ID }}
        XERO_CLIENT_SECRET: ${{ secrets.XERO_CLIENT_SECRET }}
        GOOGLE_SHEETS_SPREADSHEET_ID: ${{ secrets.GOOGLE_SHEETS_SPREADSHEET_ID }}
      run: python app.py

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: execution-logs
        path: |
          invoice_automation.log
          *.log
        retention-days: 7