name: Invoice Automation

on:
  schedule:
    - cron: '10 20 * * *'  # 7:10 AM Melbourne Time in UTC (adjusted for daylight saving)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Invoice Automation Script
        env:
          XERO_CLIENT_ID: ${{ secrets.XERO_CLIENT_ID }}
          XERO_CLIENT_SECRET: ${{ secrets.XERO_CLIENT_SECRET }}
          XERO_ACCESS_TOKEN: ${{ secrets.XERO_ACCESS_TOKEN }}
          XERO_REFRESH_TOKEN: ${{ secrets.XERO_REFRESH_TOKEN }}
          XERO_TENANT_ID: ${{ secrets.XERO_TENANT_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          GOOGLE_SHEETS_SPREADSHEET_ID: ${{ secrets.GOOGLE_SHEETS_SPREADSHEET_ID }}
        run: |
          python main.py
