name: Invoice Automation

on:
  schedule:
    # Runs at 7:10 AM Melbourne time (21:10 UTC previous day)
    - cron: '10 21 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  create-invoices:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install Werkzeug==2.0.3
        pip install Flask==2.0.1
        pip install numpy==1.24.3
        pip install pandas==1.5.3
        pip install -r requirements.txt

    - name: Create config files
      run: |
        echo "${{ secrets.XERO_CONFIG }}" > config.py
        echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json

    - name: Run invoice creation
      env:
        GOOGLE_SHEETS_SPREADSHEET_ID: ${{ secrets.GOOGLE_SHEETS_SPREADSHEET_ID }}
      run: |
        python -c "
        import sys
        import os
        print('Python version:', sys.version)
        print('Current working directory:', os.getcwd())
        print('Directory contents:', os.listdir('.'))
        "
        python app.py

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: execution-logs
        path: |
          invoice_automation.log
          *.log
        retention-days: 7